apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

resources:
  - ../../secrets
  # ---
  - ../../base/tailscale-operator
  # ---
  - ../../base/opencloud
  - opencloud
  # ---
  - ../../base/jellyfin
  - jellyfin
  # ---
  - ../../base/vaultwarden
  - vaultwarden
