apiVersion: v1

kind: Service

metadata:
  namespace: jellyfin
  name: jellyfin-app-service
  labels:
    app: jellyfin-app

spec:
  selector:
    app: jellyfin-app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8096
