apiVersion: apps/v1

kind: Deployment

metadata:
  namespace: keycloak
  name: keycloak-app-deployment
  labels:
    app: keycloak-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-app
  template:
    metadata:
      labels:
        app: keycloak-app
    spec:
      containers:
        - name: keycloak-app
          image: keycloak/keycloak:26.5
          args: ["start"]
          envFrom:
            - secretRef:
                name: keycloak-secrets
