apiVersion: v1

kind: Service

metadata:
  namespace: keycloak
  name: keycloak-app-service
  labels:
    app: keycloak-app

spec:
  selector:
    app: keycloak-app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
