apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  namespace: opencloud
  name: opencloud-app-ingress
  labels:
    app: opencloud

spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: opencloud-app-service
      port:
        number: 9200
  tls:
    - hosts:
        - opencloud
