apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  namespace: vaultwarden
  name: vaultwarden-app-ingress
  labels:
    app: vaultwarden-app

spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: vaultwarden-app-service
      port:
        number: 80
  tls:
    - hosts:
        - vaultwarden
