apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

resources:
  - namespace.yaml
  - database/deployment.yaml
  - database/pvc.yaml
  - database/service.yaml
  - app/deployment.yaml
  - app/service.yaml
