apiVersion: apps/v1

kind: Deployment

metadata:
  namespace: vaultwarden
  name: vaultwarden-app-deployment
  labels:
    app: vaultwarden-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden-app
  template:
    metadata:
      labels:
        app: vaultwarden-app
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:latest
          envFrom:
            - secretRef:
                name: vaultwarden-secrets
          volumeMounts:
            - name: vaultwarden-storage
              mountPath: /data
              subPath: data
      volumes:
        - name: vaultwarden-storage
          persistentVolumeClaim:
            claimName: vaultwarden-app-pvc
