apiVersion: v1

kind: Service

metadata:
  namespace: vaultwarden
  name: vaultwarden-app-service
  labels:
    app: vaultwarden-app

spec:
  selector:
    app: vaultwarden-app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
