apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  # tailscale
  - name: tailscale-secrets
    namespace: tailscale
    envs:
      - .env.tailscale
    options:
      labels:
        app.kubernetes.io/part-of: homecloud

  # opencloud
  - name: opencloud-secrets
    namespace: opencloud
    envs:
      - .env.opencloud
    options:
      labels:
        app.kubernetes.io/part-of: homecloud

  # vaultwarden
  - name: vaultwarden-secrets
    namespace: vaultwarden
    envs:
      - .env.vaultwarden
    options:
      labels:
        app.kubernetes.io/part-of: homecloud
