apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  # opencloud
  - name: opencloud-secrets
    namespace: opencloud
    envs:
      - .env
    options:
      labels:
        app.kubernetes.io/part-of: homecloud
