apiVersion: apps/v1

kind: Deployment

metadata:
  namespace: keycloak
  name: keycloak-database-deployment
  labels:
    app: keycloak-database

spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-database
  template:
    metadata:
      labels:
        app: keycloak-database
    spec:
      containers:
        - name: keycloak-database
          image: postgres:18-alpine
          envFrom:
            - secretRef:
                name: keycloak-secrets
          volumeMounts:
            - name: keycloak-database-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: keycloak-database-storage
          persistentVolumeClaim:
            claimName: keycloak-database-pvc
